apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-api
  labels:
    app: ocean-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocean-api
  template:
    metadata:
      labels:
        app: ocean-api
    spec:
      containers:
      - name: ocean-api
        image: jspruancedome/ocean-api
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ocean-api-service
spec:
  selector:
    app: ocean-api
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000