apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: getting-started
spec:
  taskRef:
    name: create-webhook
  params:
  - name: GitHubOrg
    value: ""
  - name: GitHubUser
    value: "jspruance"
  - name: GitHubRepo
    value: "ulmaceae"
  - name: GitHubSecretName
    value: webhook-secret
  - name: GitHubAccessTokenKey
    value: token
  - name: GitHubSecretStringKey
    value: secret
  - name: ExternalDomain
    value: 45.79.240.174
#   If you are using github enterprise, provide a value for GitHubDomain
#  - name: GitHubDomain
#    value: git.corp.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
